FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN playwright install chromium --with-deps

COPY . .

COPY docker-start.sh /docker-start.sh
RUN chmod +x /docker-start.sh

EXPOSE 8000

CMD ["/docker-start.sh"]
